// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNeQEWDGSxTr-SAkSiNhJ7Dj97WeckwCs',
    appId: '1:722261620700:web:6c4f31c1409c5d689e4119',
    messagingSenderId: '722261620700',
    projectId: 'fir-methods-9cc92',
    authDomain: 'fir-methods-9cc92.firebaseapp.com',
    storageBucket: 'fir-methods-9cc92.appspot.com',
    measurementId: 'G-8TLLBX69LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV9mPWqOD3C-mWQ3xRSsKWAD1O2T4TKvA',
    appId: '1:722261620700:android:f960b46dd464fe0b9e4119',
    messagingSenderId: '722261620700',
    projectId: 'fir-methods-9cc92',
    storageBucket: 'fir-methods-9cc92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKxZNWLPiFPhe2DMc8lP17kx4BS5gGA5k',
    appId: '1:722261620700:ios:194d6606ff3374cb9e4119',
    messagingSenderId: '722261620700',
    projectId: 'fir-methods-9cc92',
    storageBucket: 'fir-methods-9cc92.appspot.com',
    androidClientId: '722261620700-gumvnsf83rpj0m6o8bl34js9u60p2des.apps.googleusercontent.com',
    iosClientId: '722261620700-chrpou7qruh53dsn752jl5qaj84pd5k1.apps.googleusercontent.com',
    iosBundleId: 'com.example.kinema',
  );
}
